services:
  - type: web
    name: elextercores-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: BOT_NAME
        value: ELEXTERCORES FLEX
      - key: BOT_OWNER
        value: NĞỊJẢ_NĨJ