services:
  - type: web
    name: elextercores-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: USE_YARN
        value: false